//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace JetFlyService_Test.TestedService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="JetFlyServiceSoap", Namespace="http://alexshestakov.com/")]
    public partial class JetFlyService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PostBase64EncodedJpegImageOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public JetFlyService() {
            this.Url = global::JetFlyService_Test.Properties.Settings.Default.JetFlyService_Test_TestedService_JetFlyService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PostBase64EncodedJpegImageCompletedEventHandler PostBase64EncodedJpegImageCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://alexshestakov.com/PostBase64EncodedJpegImage", RequestNamespace="http://alexshestakov.com/", ResponseNamespace="http://alexshestakov.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PostBase64EncodedJpegImage(string base46EncodedJpegImage) {
            object[] results = this.Invoke("PostBase64EncodedJpegImage", new object[] {
                        base46EncodedJpegImage});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PostBase64EncodedJpegImageAsync(string base46EncodedJpegImage) {
            this.PostBase64EncodedJpegImageAsync(base46EncodedJpegImage, null);
        }
        
        /// <remarks/>
        public void PostBase64EncodedJpegImageAsync(string base46EncodedJpegImage, object userState) {
            if ((this.PostBase64EncodedJpegImageOperationCompleted == null)) {
                this.PostBase64EncodedJpegImageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostBase64EncodedJpegImageOperationCompleted);
            }
            this.InvokeAsync("PostBase64EncodedJpegImage", new object[] {
                        base46EncodedJpegImage}, this.PostBase64EncodedJpegImageOperationCompleted, userState);
        }
        
        private void OnPostBase64EncodedJpegImageOperationCompleted(object arg) {
            if ((this.PostBase64EncodedJpegImageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostBase64EncodedJpegImageCompleted(this, new PostBase64EncodedJpegImageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PostBase64EncodedJpegImageCompletedEventHandler(object sender, PostBase64EncodedJpegImageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostBase64EncodedJpegImageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostBase64EncodedJpegImageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591